version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: database
    volumes:
     - /tmp/data/mysql:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: top-secret
     MYSQL_DATABASE: TBZ
     MYSQL_USER: AJB
     MYSQL_PASSWORD: TBZ123
  web:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    container_name: webserver
    ports:
     - '3306:3306'
    restart: always