version: '3.7'
services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: top-secret
     MYSQL_DATABASE: wordpress
     MYSQL_USER: Benita
     MYSQL_PASSWORD: 1234
    volumes:
     - mysql:/var/lib/mysql

