version: '3.7'
services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: top-secret
     MYSQL_DATABASE: wordpress
     MYSQL_USER: Benita
     MYSQL_PASSWORD: 1234
    volumes:
     - mysql:/var/lib/mysql

  wordpress:
    depends_on:
     - mysql_db
    image: wordpress:latest
    restart: always
    ports:
     - "8081:80"
    environment:
     WORDPRESS_DB_HOST: mysql_db:3306
     WORDPRESS_DB_USER: Benita
     WORDPRESS_DB_PASSWORD: 1234
     WORDPRESS_DB_Name: wordpress
    volumes:
     - "./:/var/www/html"

